booking/urls.py
from django.urls import path
from booking import views

app_name='booking'
urlpatterns = [
    path('search/',views.doctor_list, name="doctor_list"),
    path('search/doctor-search/',views.search_doctor, name="search_doctor"),
    path('search/<pk>/',views.doctor_detail, name='doctor_detail'),
    path('enter_paitent_details/<pk>/',views.enter_paitent_details, name='enter_paitent_details'),
    path('view_paitent_details/<pk>/',views.view_paitent_details, name='view_paitent_details'),
    # path('make_slot/<pk>',views.make_slot,name='make_slot'),
    # path('booking_confirmation/<pk>/', views.booking_confirmation, name='booking_confirmation')
    path('booking_confirmation/<pk>/', views.AppointmentDetialsCreate.as_view(), name='booking_confirmation'),\
    path('ajax/load-slots/', views.load_time, name='ajax_load_slots'),


]

prescription/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
app_name='prescription'
urlpatterns=[
    path('',views.index,name='index'),
    url(r'^prescription_add/(?P<appointment_id>[0-9]+)$',views.PrescriptionCreate.as_view(),name='Prescription_Add1'),
    path('prescription_add/',views.make_prescription,name='Prescription_Add'),
    url(r'^(?P<pk>[0-9]+)/$',views.DetailView.as_view(),name='detail'),
    url(r'^(?P<prescription_id>[0-9]+)/create_item/$', views.create_item, name='create_item'),
    path('name-autocomplete/',views.MedicineAutocomplete.as_view(),name='name-autocomplete'),
    url(r'^(?P<prescription_id>[0-9]+)/print/$', views.print, name='print'),

]

rmp/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from rmp.views import user_register, new_user_reg
from django.contrib.auth import views as auth_views
from users import views as user_views

app_name='rmp'

urlpatterns=[
    path('make_rmp_profile/',views.make_profile,name='make_rmp_profile'),
    path('modify_rmp_profile/',views.modify_profile,name='modify_rmp_profile'),
    path('show_rmp_profile/',views.Show_Profile,name='show_rmp_profile'),
    path('login/',views.login_page,name='login_rmp_profile'),
   # path('register/',views.register_page,name='make_rmp_profile'),
   url(r'^rmp/register/$',views.user_register , name='user_register' ),
   url(r'^rmp/new_user_reg/$',views.new_user_reg , name='new_user_reg' ),
   url(r'^password/change/$',
        auth_views.PasswordChangeView.as_view(),
        name='password_change'),
    url(r'^password/change/done/$',
        auth_views.PasswordChangeDoneView.as_view(),
        name='password_change_done'),
    url(r'^login/password/reset/$',
        auth_views.PasswordResetView.as_view(),
        name='password_reset'),
    url(r'^password/reset/done/$',
        auth_views.PasswordResetDoneView.as_view(),
        name='password_reset_done'),
    url(r'^password/reset/\
        (?P<uidb64>[0-9A-Za-z_\-]+)/\
        (?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'),
    url(r'^password/reset/complete/$',
        auth_views.PasswordResetCompleteView.as_view(),
        name='password_reset_complete'),

    ]

website/urls.py
from django.contrib import admin
from django.conf.urls import include
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import home, contact_page, login_page, about, contact, how_we_work,doctor_home,doctor_contact
from django.conf.urls import url
from django.conf import settings
from django.contrib import admin
from django.conf.urls import url, include


from .views import home_page, login_page,log_out,user_register, new_user_reg

from django.contrib.auth import views as auth_views
from users import views as user_views

# app_name='website'
urlpatterns = [

    path('', home, name='home'),
    path('admin/',admin.site.urls),
    path('logout/', log_out, name='logout'),
    path('contact_page/', contact_page , name='contact_page'),
    path('contact/', contact , name='contact'),
    path('doctor_contact/', doctor_contact , name='contact_doctor'),
    path('about/', about , name='about'),
    path('how_we_work/', how_we_work , name='how_we_work'),
    url(r'^doctor_home/$',doctor_home, name='doctor_home'),
    # url(r'^doctor_home/$',doctor_verification_required, name='doctor_verification_required'),
    url(r'^doctor/', include(("doctor_home.url","doctor"), namespace= 'doctor')),
    #(r'^$',home_page , name='home_page'),
    url(r'^login/$', login_page, name='login' ),
    url(r'^doctor/register/$',user_register , name='user_register' ),
    url(r'^doctor/new_user_reg/$',new_user_reg , name='new_user_reg' ),
    url(r'^password/change/$',
        auth_views.PasswordChangeView.as_view(),
        name='password_change'),
    url(r'^password/change/done/$',
        auth_views.PasswordChangeDoneView.as_view(),
        name='password_change_done'),
    url(r'^login/password/reset/$',
        auth_views.PasswordResetView.as_view(),
        name='password_reset'),
    url(r'^password/reset/done/$',
        auth_views.PasswordResetDoneView.as_view(),
        name='password_reset_done'),
    url(r'^password/reset/\
        (?P<uidb64>[0-9A-Za-z_\-]+)/\
        (?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'),
    url(r'^password/reset/complete/$',
        auth_views.PasswordResetCompleteView.as_view(),
        name='password_reset_complete'),

    path('restframework/', include('restframework.urls')),

    path('shoponline/', include('shoppingPortalApp.urls')),
    path('shoponline/', include('shopping_cart.urls')),
    path('payment/', include('payment.urls')),

    path('profile/',include('doctor_profile.urls')),
    path('disease/',include('disease.urls')),
    path('prescription/',include('prescription.urls')),
    path('rmp/booking/',include('booking.urls')),
    path('appointments/',include('show_appointments.urls'),name='show_appointments'),
    path('work_history/',include('work_history.urls')),
    path('rmp_work_history/',include('rmp_work_history.urls')),
    #url(r'^activate/$', activate, name='activate'),

    #path('account-activation-email-sent', account_activation_email_sent, name='account_activation_email_sent'),
   # path('activate/<uidb64>/token>', activate_account, name='activate'),
  #  path('resend-activation-link', generate_new_activation_link, name='resend_activation_link'),



    path('', include('myapp.urls'), name='myapp'),
    path('users/',include('users.urls'), name='users'),
    path('rmp/', include('rmp.urls')),
]

if settings.DEBUG:

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

work_history/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
app_name='work_history'
urlpatterns=[
path('',views.index1,name='index'),
];

booking/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.core.validators import MaxValueValidator, MinValueValidator
from django.contrib.auth.models import User
from rmp.models import rmpContact
import uuid
from uuid import uuid4
from doctor_profile.models import Profile,BookingDate,Slot
from prescription.models import Prescription
# Create your models here.

from uuid import uuid4

def generateUUID():
    return str(uuid4())

class PaitentDetails(models.Model):

    Male = 'Male'
    Female = 'Female'

    GENDER_CHOICES = (
        (Male, 'Male'),
        (Female, 'Female'),

    )


    user = models.ForeignKey(User, on_delete=models.CASCADE,null=True,blank=True)
    doctor_id=models.ForeignKey(Profile,max_length=250, null=True,blank=True, on_delete=models.CASCADE)
    first_name=models.CharField(max_length=250)
    last_name=models.CharField(max_length=500)
    age=models.IntegerField()
    gender=models.CharField(max_length=10, choices=GENDER_CHOICES)
    mobile_no=models.BigIntegerField()
    symptoms=models.CharField(max_length=250)
    description_of_illness=models.CharField(max_length=250)
    checkout_id = models.CharField(default=generateUUID, max_length=36, unique=True,editable=False)
    doctor_name=models.CharField(max_length=150)



    def __str__(self):
    	return str(self.id)

    def get_absolute_url_booking_confirmation(self):
        return reverse('booking:booking_confirmation',kwargs={'pk':self.pk})




class AppointmentDetials(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,null=True,blank=True)
    viedo_chat_link=models.CharField(max_length=100)
    appointment_slot=models.CharField(max_length=150)
    doctor_id=models.ForeignKey(Profile,max_length=250, null=True,blank=True, on_delete=models.CASCADE)
    date=models.ForeignKey(BookingDate,max_length=250, null=True,blank=True, on_delete=models.CASCADE)
    time=models.ForeignKey(Slot,max_length=250,null=True,blank=True, on_delete=models.CASCADE)
    appointment_id=models.CharField(max_length=20)
    transaction_id=models.CharField(max_length=250)
    paitent=models.ForeignKey(PaitentDetails, on_delete=models.CASCADE, null=True, blank=True)
    is_attended=models.BooleanField(default=False)
    prescription=models.ForeignKey(Prescription,on_delete=models.CASCADE,null=True,blank=True)

    def __str__(self):
        return str(self.pk)

booking/forms.py
from django import forms
from .models import PaitentDetails,AppointmentDetials
from doctor_profile.models import BookingDate

class Add_PaitentDetails(forms.ModelForm):
    class Meta:
        model=PaitentDetails
        fields='__all__'
        exclude=('user','doctor_id','doctor_name',)

    def clean_mobile_no(self):
        mobile_no = self.cleaned_data['mobile_no']
        if len(str(mobile_no)) != 10:
            raise forms.ValidationError('enter  a 10 digit number')
        return self.cleaned_data['mobile_no']

    def clean_symptoms(self):
        symptoms = self.cleaned_data['symptoms']
        if len(str(symptoms)) < 10:
            raise forms.ValidationError('Symptoms should be atleast 10 characters long')
        return self.cleaned_data['symptoms']

class Add_PatientToAppointment(forms.ModelForm):
    class Meta:
        model = AppointmentDetials
        fields='__all__'

class AppointmentCreateForm(forms.ModelForm):
    class Meta:
        model=AppointmentDetials
        #fields=['doctor_id','appointment_id','paitent','date','time','transaction_id','viedo_chat_link']
        fields=['date','time']

    def __init__(self, *args, **kwargs):
        doctor_id = kwargs.pop('other_variable')

        super(AppointmentCreateForm, self).__init__(*args, **kwargs)
        self.fields['date'] = forms.ModelChoiceField(
            queryset=BookingDate.objects.filter(doctor=doctor_id)
        )

booking/views.py
from django.contrib import messages
from django.shortcuts import render,get_object_or_404,redirect
from doctor_profile.models import Profile,BookingDate
from django.http import HttpResponse
from .forms import *
from .models import PaitentDetails,AppointmentDetials
import random
from django.db.models import Max
from django.views.generic import FormView, CreateView
from doctor_profile.models import BookingDate,Slot
from django.contrib.auth.decorators import login_required
from doctor_profile.models import Profile
from django.contrib import messages
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode

@login_required(login_url=('rmp:login_rmp_profile'))
def doctor_list(request):
	doctors = Profile.objects.all()
	context = {

	   "doctor" : doctors,
	}
	return render(request, 'booking/doctor_list.html',context=context)



@login_required(login_url=('rmp:login_rmp_profile'))
def doctor_detail(request, pk):
    instance = get_object_or_404(Profile, pk=pk)
    context = {
        "doctor" : instance,
    }
    return render(request, 'booking/doctor_detail.html',context=context)

@login_required(login_url=('rmp:login_rmp_profile'))
def search_doctor(request):
	search = request.GET['searching_doctor']
	temp = search.upper()
	doctors = Profile.objects.all()
	k_name = 404
	k_speciality = 404
	for doctor in doctors:
		if doctor.first_name.upper() == temp:
			k_name = doctor.id
	if(k_name==404):
		for doctor in doctors:
			if doctor.last_name.upper() == temp:
				k_name = doctor.id
	speciality_doctors = Profile.objects.filter(speciality=temp)
	if(speciality_doctors.count()):
		k_speciality = 1
	if(k_name==404):
		if(k_speciality==1):
			context = {
			"key" : False,
			"key1": True,
			"speciality_doctors":speciality_doctors,
			}
		else:
			context = {
			"key" : False,
			"query":search,
			"key1" : False,
			}
	else:
		if(k_speciality==1):
			context = {
			"key" : True,
			"searched_doctor" : get_object_or_404(Profile,id=k_name),
			"key1": True,
			"speciality_doctors":speciality_doctors,
			}
		else:
			context = {
			"key" : True,
			"searched_doctor" : get_object_or_404(Profile,id=k_name),
			"key1" : False,
			}
	print()
	print(context)
	print()
	return render(request, 'booking/search.html',context)

@login_required(login_url=('rmp:login_rmp_profile'))
def enter_paitent_details(request, pk):
	user=request.user
	instance = get_object_or_404(Profile, pk=pk)

	if request.method=="POST":
		form=Add_PaitentDetails(request.POST, request.FILES)
		if form.is_valid():


			paitent_details=form.save(commit=False)
			#request.session['patient_id']=paitent_details.pk
			paitent_details.user=user
			paitent_details.doctor_id=instance
			paitent_details.save()
			print(paitent_details)

			return redirect('booking:view_paitent_details', pk=paitent_details.id)
	else:
		form  = Add_PaitentDetails(initial={ 'user':user, 'doctor_id':pk})
		#form1 = Add_PatientToAppointment(initial={'patient':form})
	context = {
        "form":form,
     }
	return render(request, 'booking/enter_paitent_details.html',context=context)


@login_required(login_url=('rmp:login_rmp_profile'))
def view_paitent_details(request, pk):
	instance=get_object_or_404(PaitentDetails, pk=pk)
	context={
	    "paitent":instance
	}
	return render(request, 'booking/show_paitent_details.html',context=context)

@login_required(login_url=('rmp:login_rmp_profile'))
def load_time(request):
	print('**')
	date_id = request.GET.get('date')
	print(date_id)
	slots = Slot.objects.filter(date_id=date_id).filter(slot_status=False)
	print(slots)
	return render(request, 'booking/slot_dropdown_list_options.html', {'slots': slots})



class AppointmentDetialsCreate(CreateView):
	model=AppointmentDetials
	form_class = AppointmentCreateForm
	other_variable=None
	# fields=['doctor_id','appointment_id','paitent','date','time','transaction_id']
	#################################TO PASS INITIAL VALUES ############
	def get_form_kwargs(self):
		self.pk=self.kwargs['pk']
		#user = request.user
		instance=get_object_or_404(PaitentDetails,pk=self.pk)
		self.doctor_id=instance.doctor_id
		doctor_id=self.doctor_id
		kwargs = super(AppointmentDetialsCreate, self).get_form_kwargs()
		kwargs.update({'other_variable': self.doctor_id})
		return kwargs

	def get_initial(self):
		pass

	def form_valid(self, form):
		user=self.request.user
		appointment = form.save(commit=False)
		print('##')
		print(appointment)

		self.pk=self.kwargs['pk']

		string= random.randint(100000000,10000000000000)
		viedo_chat_link="https://appr.tc/r/"+str(string)
		max_id=AppointmentDetials.objects.all().aggregate(Max('appointment_id'))
		if list(max_id.values())[0] == None:
			value=0
		else:
			value=int(list(max_id.values())[0])
		appointment_id=value+1

		max_id=AppointmentDetials.objects.all().aggregate(Max('transaction_id'))
		if list(max_id.values())[0] == None:
			value=100000
		else:
			value=int(list(max_id.values())[0])
		transaction_id=value+1
		instance=get_object_or_404(PaitentDetails,pk=self.pk)

		self.doctor_id=instance.doctor_id
		appointment.user=user
		appointment.doctor_id=self.doctor_id
		appointment.appointment_id=appointment_id
		appointment.paitent=instance
		appointment.transaction_id=transaction_id
		appointment.viedo_chat_link=viedo_chat_link
		date=appointment.date
		time=appointment.time
		slots = Slot.objects.filter(date_id=date).filter(start_time=time).first()
		slots.slot_status=True
		slots.save()
		appointment.save()
		
		context={

		    "object":appointment,
		   
		}
		return render(self.request,'booking/booking_confirmation.html', context=context)
		# return super(AppointmentDetialsCreate, self).form_valid(form)


def booking_confirmation(request, pk):
	print("**")
	user=request.user
	string= random.randint(100000000,10000000000000)
	viedo_chat_link="https://appr.tc/r/"+str(string)
	max_id=AppointmentDetials.objects.all().aggregate(Max('appointment_id'))
	if list(max_id.values())[0] == None:
		value=0
	else:
		value=int(list(max_id.values())[0])
	appointment_id=value+1

	max_id=AppointmentDetials.objects.all().aggregate(Max('transaction_id'))
	if list(max_id.values())[0] == None:
		value=100000
	else:
		value=int(list(max_id.values())[0])
	transaction_id=value+1
	instance=get_object_or_404(PaitentDetails,pk=pk)
	doctor_id=instance.doctor_id

	#patient_id=request.session['patient_id']
	#patient_obj=get_object_or_404(PaitentDetails,pk=patient_id)
	obj=AppointmentDetials.objects.create(user=user,viedo_chat_link=viedo_chat_link,transaction_id=transaction_id,appointment_id=appointment_id,doctor_id=doctor_id,paitent=instance)
	obj.save()

	context={
	   "paitent":instance,
	    "object":obj,
	}
	return render(request,'booking/booking_confirmation.html', context=context)

booking/templates/booking/AppointmentDetials_form.html
<style>
.card {
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
  max-width: 400px;
  margin: auto;
  /* text-align: center; */
  font-family: arial;
}

.title {
  color: grey;
  font-size: 18px;
}

button {
  border: none;
  outline: 0;
  display: inline-block;
  padding: 8px;
  color: white;
  background-color: #000;
  text-align: center;
  cursor: pointer;
  width: 100%;
  font-size: 18px;
}

a {
  text-decoration: none;
  font-size: 22px;
  color: black;
}

button:hover, a:hover {
  opacity: 0.7;
}
</style>

{% extends 'base.html' %}


{% load static %}
-- NAV BAR -->
      <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
      <div class="container">
        <a href='{% url "home" %}' class="navbar-brand"><b>SMART HEALTHCARE SYSTEM</b></a>
        <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a href='{% url "doctor_home" %}' class="nav-link">Home</a>
            </li>

<!--
            <li class="nav-item">
              <a href='{% url "contact_doctor" %}' class="nav-link">Contact</a>
            </li> -->
            <li class="nav-item">
              <a href='{% url "prescription:Prescription_Add" %}' class="nav-link">Make Prescription</a>
            </li>
            <li class="nav-item">
              <a href='{% url "work_history:index" %}' class="nav-link">Work History</a>
            </li>
            <li class="nav-item active">
              <a href='{% url "logout" %}' class="nav-link">Logout</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

<meta name="viewport" content="width=device-width, initial-scale=1">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

  {% block prescription_home %}
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
  <div class="container">
    <a href="index.html" class="navbar-brand"><b>SMART HEALTHCATRE SYSTEM</b></a>
    <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a href='{% url "doctor_home" %}' class="nav-link">Home</a>
        </li>

        <li class="nav-item">
          <a href='{% url "how_we_work" %}' class="nav-link">How we work</a>
        </li>
        <li class="nav-item">
          <a href='{% url "contact" %}' class="nav-link">Contact</a>
        </li>
        <li class="nav-item">
          <a href='{% url "prescription:Prescription_Add" %}' class="nav-link">Make Prescription</a>
        </li>
        <li class="nav-item">
          <a href='{% url "work_history:index" %}' class="nav-link">Work History</a>
        </li>
        <li class="nav-item active">
          <a href='{% url "logout" %}' class="nav-link">Logout</a>
        </li>
      </ul>
    </div>
  </div>
  </nav>

  <div class="container-fluid" style="background-image:url({% static 'img/prescription.jpg' %});background-repeat; background-size:cover;height:680px">

    <!-- <div class="row ">
      <div class="col-sm-6 col-md-6 ">
        <div class="panel-body ">
          <form class="form-horizonatal" action="" method="post">
            {% csrf_token %}
            {% include 'prescription/prescription-template.html' %}
            <div class="form-group">
              <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-success">Submit </button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div> -->


<br><br><br><br>




    <div class="card mx-auto"><br><br>
      <form class="form-horizonatal" action="" method="post" id="AppointmentCreateForm" data-slots-url="{% url 'booking:ajax_load_slots' %}" novalidate>
        {% csrf_token %}
        {% include 'prescription/prescription-template.html' %}
        <!-- <table>
          {{ form.as_table }}
      </table> -->
        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-12">
            <button type="submit" class="btn btn-success btn-default">Submit </button>
            </div>
            </div>
        </form>
        <br><br><br><br><br>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
  $("#id_date").change(function () {
    var url = $("#AppointmentCreateForm").attr("data-slots-url");  // get the url of the `load_cities` view
    var dateId = $(this).val();  // get the selected 

    $.ajax({                       // initialize 
      url: url,               
      data: {
        'date': dateId       
      },
      success: function (data) {   // `data` is the return 
        $("#id_time").html(data);  // replace the contents  with the data that came from the server
     
      }
    });

  });
</script>

    </div>
    </div>

{% endblock %}

booking/templates/booking/prescription-template.html
{% for field in form %}
  <div class="form-group ">
    <div class="col-sm-offset-2 col-sm-10">
      <span class="text-danger small">{{field.errors}}</span>
    </div>
    <label class="control-label col-sm-3">{{ field.label_tag}}</label>
    <label class="col-sm-8">{{ field }}</label>
  </div>
{% endfor %}

booking/templates/booking/slot_dropdown_list_options.html
<!-- <option value="">---------</option> -->
{% for slot in slots %}
<option value="{{ slot.pk }}">{{ slot.start_time }}</option>

{% endfor %}