rmp/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from rmp.views import user_register, new_user_reg
from django.contrib.auth import views as auth_views
from users import views as user_views

app_name='rmp'

urlpatterns=[
    path('make_rmp_profile/',views.make_profile,name='make_rmp_profile'),
    path('modify_rmp_profile/',views.modify_profile,name='modify_rmp_profile'),
    path('show_rmp_profile/',views.Show_Profile,name='show_rmp_profile'),
    path('login/',views.login_page,name='login_rmp_profile'),
   # path('register/',views.register_page,name='make_rmp_profile'),
   url(r'^rmp/register/$',views.user_register , name='user_register' ),
   url(r'^rmp/new_user_reg/$',views.new_user_reg , name='new_user_reg' ),
   url(r'^password/change/$',
        auth_views.PasswordChangeView.as_view(),
        name='password_change'),
    url(r'^password/change/done/$',
        auth_views.PasswordChangeDoneView.as_view(),
        name='password_change_done'),
    url(r'^login/password/reset/$',
        auth_views.PasswordResetView.as_view(),
        name='password_reset'),
    url(r'^password/reset/done/$',
        auth_views.PasswordResetDoneView.as_view(),
        name='password_reset_done'),
    url(r'^password/reset/\
        (?P<uidb64>[0-9A-Za-z_\-]+)/\
        (?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'),
    url(r'^password/reset/complete/$',
        auth_views.PasswordResetCompleteView.as_view(),
        name='password_reset_complete'),

    ]

shopping_cart/urls.py
from django.urls import path
from shopping_cart import views

app_name = 'shopping_cart'

urlpatterns = [
	path('add-to-cart/<item_id>/',views.add_to_cart,name='add_to_cart'),
	path('order-summary/',views.order_summary,name='order_summary'),
	path('enter-address/',views.enter_address,name='enter_address'),
	# path('delete/<item_id>/',views.delete_from_cart,name='delete_from_cart'),
	# path('delete2/<item_id>/',views.delete_from_cart2,name='delete_from_cart2'),
	path('purchase-success/<payment_mode>/',views.purchase_success,name='purchase_success'),
	path('order-history/',views.show_order_history,name='order'),
	path('order-summary-ajax/',views.order_summary_ajax,name='order_summary_ajax'),

]

website/urls.py
from django.contrib import admin
from django.conf.urls import include
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import home, contact_page, login_page, about, contact, how_we_work,doctor_home,doctor_contact
from django.conf.urls import url
from django.conf import settings
from django.contrib import admin
from django.conf.urls import url, include


from .views import home_page, login_page,log_out,user_register, new_user_reg

from django.contrib.auth import views as auth_views
from users import views as user_views

# app_name='website'
urlpatterns = [

    path('', home, name='home'),
    path('admin/',admin.site.urls),
    path('logout/', log_out, name='logout'),
    path('contact_page/', contact_page , name='contact_page'),
    path('contact/', contact , name='contact'),
    path('doctor_contact/', doctor_contact , name='contact_doctor'),
    path('about/', about , name='about'),
    path('how_we_work/', how_we_work , name='how_we_work'),
    url(r'^doctor_home/$',doctor_home, name='doctor_home'),
    # url(r'^doctor_home/$',doctor_verification_required, name='doctor_verification_required'),
    url(r'^doctor/', include(("doctor_home.url","doctor"), namespace= 'doctor')),
    #(r'^$',home_page , name='home_page'),
    url(r'^login/$', login_page, name='login' ),
    url(r'^doctor/register/$',user_register , name='user_register' ),
    url(r'^doctor/new_user_reg/$',new_user_reg , name='new_user_reg' ),
    url(r'^password/change/$',
        auth_views.PasswordChangeView.as_view(),
        name='password_change'),
    url(r'^password/change/done/$',
        auth_views.PasswordChangeDoneView.as_view(),
        name='password_change_done'),
    url(r'^login/password/reset/$',
        auth_views.PasswordResetView.as_view(),
        name='password_reset'),
    url(r'^password/reset/done/$',
        auth_views.PasswordResetDoneView.as_view(),
        name='password_reset_done'),
    url(r'^password/reset/\
        (?P<uidb64>[0-9A-Za-z_\-]+)/\
        (?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'),
    url(r'^password/reset/complete/$',
        auth_views.PasswordResetCompleteView.as_view(),
        name='password_reset_complete'),

    path('restframework/', include('restframework.urls')),

    path('shoponline/', include('shoppingPortalApp.urls')),
    path('shoponline/', include('shopping_cart.urls')),
    path('payment/', include('payment.urls')),

    path('profile/',include('doctor_profile.urls')),
    path('disease/',include('disease.urls')),
    path('prescription/',include('prescription.urls')),
    path('rmp/booking/',include('booking.urls')),
    path('appointments/',include('show_appointments.urls'),name='show_appointments'),
    path('work_history/',include('work_history.urls')),
    path('rmp_work_history/',include('rmp_work_history.urls')),
    #url(r'^activate/$', activate, name='activate'),

    #path('account-activation-email-sent', account_activation_email_sent, name='account_activation_email_sent'),
   # path('activate/<uidb64>/token>', activate_account, name='activate'),
  #  path('resend-activation-link', generate_new_activation_link, name='resend_activation_link'),



    path('', include('myapp.urls'), name='myapp'),
    path('users/',include('users.urls'), name='users'),
    path('rmp/', include('rmp.urls')),
]

if settings.DEBUG:

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

work_history/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
app_name='work_history'
urlpatterns=[
path('',views.index1,name='index'),
];

rmp/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.core.validators import MaxValueValidator, MinValueValidator
from django.contrib.auth.models import User

from shoppingPortalApp.models import medicine
# Create your models here.


class rmpContact(models.Model):

    Male = 'Male'
    Female = 'Female'

    GENDER_CHOICES = (
        (Male, 'Male'),
        (Female, 'Female'),

    )


    user = models.OneToOneField(User, on_delete=models.CASCADE,null=True,blank=True)
    verified=models.BooleanField(default=True)
    profile_photo=models.ImageField(upload_to='media_/profile_pic/')
    first_name=models.CharField(max_length=250)
    last_name=models.CharField(max_length=500)
    gender=models.CharField(max_length=10, choices=GENDER_CHOICES)
    email_id=models.CharField(max_length=250)
    mobile_no=models.BigIntegerField()
    qualification=models.CharField(max_length=250)
    locality=models.CharField(max_length=250)
    hospital=models.CharField(max_length=250)

    medicines = models.ManyToManyField(medicine, blank=True)

    def __str__(self):
        return str(self.id)

    def get_absolute_url(self):
        return reverse('myapp:myapp-fullrmplist',kwargs={'pk':self.pk})
    def get_absolute_url_verify(self):
        return reverse('myapp:verify-rmp',kwargs={'pk':self.pk})
    def get_absolute_url_rmp_upcoming_appointments(self):
        return reverse('myapp:rmp_upcoming_appointments', kwargs={'pk': self.pk})
    def get_absolute_url_rmp_attended_appointments(self):
        return reverse('myapp:rmp_attended_appointments', kwargs={'pk': self.pk})

    def get_absolute_url_rmp_patientdetail(self):
        return reverse('myapp:myapp-patientdetail', kwargs={'pk': self.pk})

rmp/forms.py
from django import forms
from django.contrib.auth import get_user_model
from .models import rmpContact



User=get_user_model()


class LoginForm(forms.Form):
	username=forms.CharField(widget=forms.TextInput(attrs={'class': 'form-label-group'}))
	password=forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-label-group'}))


class RegisterForm(forms.ModelForm):
	username=forms.CharField(widget=forms.TextInput(attrs={'class': 'form-label-group'}))
	email=forms.EmailField(widget=forms.TextInput(attrs={'class': 'form-label-group'}))
	password=forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-label-group'}))
	password1=forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-label-group'}))
	class Meta:
   		model=User
   		fields=('username','email','password','password1')
	def clean_username(self):
		username=self.cleaned_data.get('username')
		qs = User.objects.filter(username=username)
		if qs.exists():
			raise forms.ValidationError("username is not available please take other")
		return username
	def clean_email(self):
		email=self.cleaned_data.get('email')
		qs = User.objects.filter(email=email)
		if qs.exists():
			raise forms.ValidationError("email is not available please take other")
		return email
	def clean_password1(self):
		#data=self.cleaned_data
		password=self.cleaned_data.get('password')
		password1=self.cleaned_data.get('password1')
		if password != password1:
			raise forms.ValidationError("Passwords are not matching!!!!!!")
		return password1




class Add_Rmp_Profile(forms.ModelForm):
    # email_id=forms.CharField(widget=forms.EmailInput)
    class Meta:
        model=rmpContact
        exclude = ('user','medicines','email_id')

    def clean_mobile_no(self):
        mobile_no = self.cleaned_data['mobile_no']
        if len(str(mobile_no)) != 10:
            raise forms.ValidationError('enter  a 10 digit number')
        return self.cleaned_data['mobile_no']

rmp/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404,redirect
from django.contrib.auth import authenticate, login, get_user_model
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404,redirect
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import UserCreationForm
from django.utils.encoding import force_bytes, force_text
from .forms import  LoginForm, RegisterForm,Add_Rmp_Profile
from .models import rmpContact
from myapp.models import Rmplist,Profile
from shopping_cart.models import Order
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from django.core.mail import send_mail
from django.db import connection,IntegrityError
import random
from django.urls import reverse_lazy
from django.contrib.auth.models import User
from django.urls import reverse,reverse_lazy

def login_page(request):
	form=LoginForm(request.POST or None)
	context= {
		"form":form
	}
	if form.is_valid():
		print(form.cleaned_data)
		username=form.cleaned_data.get("username")
		password=form.cleaned_data.get("password")
		user=authenticate(request, username=username, password=password)
		if user is not None:

			print(user.is_authenticated)
			login(request, user)
			return redirect("/rmp/show_rmp_profile/")
		else:
			messages.error(request, 'Invalid login credentials')
			print("error")

	return render(request, "rmp/login.html", context=context)

def email_verify(form):
	rand_numb=random.randint(10000, 999999)
	global b
	b=str(rand_numb)
	email=[form.data['email']]
	response=send_mail("OTP for email activation",b,"smarthealthcaresystemiiits@gmail.com",email)
	return b

#User = get_user_model()
def user_register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password'])
            b=email_verify(form)
            print(b)
            username=form.data['username']
            email=form.data['email']
            password1=form.data['password']
            context={
            'username':username,
            'email':email,
            'password':password1,
            'b':b,
            }

            return render(request,'verify1.html', context)
    else:
    	form=RegisterForm()
    	messages.error(request, 'Invalid login credentials')
    context={
    'form':form
    }
    return render(request,'rmp/register.html',context)

#User = get_user_model()
def new_user_reg(request):
	if b == request.POST['token']:
		if request.method =='POST':
			username=request.POST.get('username',False)
			email=request.POST.get('email',False)
			password=request.POST.get('password',False)
			new_user=User.objects.create(username=username,email=email)
			new_user.set_password(request.POST['password'])
			new_user.save()
			login(request,new_user)
			print(new_user)
			return redirect('/rmp/make_rmp_profile/')

	else:
		return HttpResponse('Please give correct OTP')

@login_required(login_url=reverse_lazy('rmp:login_rmp_profile'))
def make_profile(request):
	user = request.user
	if request.method=="POST":

		form=Add_Rmp_Profile(request.POST, request.FILES ,initial={'email_id':user.email})

		if form.is_valid():
			profile=form.save(commit=False)
			profile.user=user
			profile.verified=False
			profile.email_id=user.email
			profile.save()

			return redirect(reverse('doctor_profile:verification'))

	else:
		form=Add_Rmp_Profile(initial={'user':user,'email_id':user.email})
	return render(request,'rmp/make_rmp_profile.html',{'form':form})

@login_required(login_url=reverse_lazy('rmp:login_rmp_profile'))
def modify_profile(request):
	user = request.user
	profile = Profile.objects.get(user=user)
	form=Add_Rmp_Profile(request.POST or None, instance=profile)
	if form.is_valid():
		form.save()
		return redirect('/show_rmp_profile/')
	return render(request,'rmp/make_rmp_profile.html',{'form':form})

@login_required(login_url=reverse_lazy('rmp:login_rmp_profile'))
def Show_Profile(request):
	user = request.user
	profile = rmpContact.objects.get(user=user)
	context={
		'profile':profile
	}
	if(profile.verified==True):
		print('&&')
		return render(request,'rmp/show_rmp_profile.html',context)
	else:
		print('%%')
		return redirect(reverse('doctor_profile:verification'))



@login_required(login_url=reverse_lazy('rmp:login_rmp_profile'))
def myOrders(request):
	user = request.user
	my_user_profile = rmpContact.objects.get(user=user)
	my_orders = Order.objects.filter(is_ordered=True, owner=my_user_profile)
	context = {
		'my_orders' : my_orders,
	}
	return render(request,'rmp/show_rmp_profile.html',context)

work_history/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404, redirect
from django.http import HttpResponse
from django.template.loader import get_template
from prescription.models import Prescription
from doctor_profile.models import Profile
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from booking.models import AppointmentDetials
@login_required(login_url=reverse_lazy('login'))
def index1(request):
    user=request.user
    profile = Profile.objects.get(user=user)
    appointments=AppointmentDetials.objects.filter(doctor_id=profile.id).filter(is_attended=True).order_by('date').order_by('time')
    first_name=profile.first_name
    last_name=profile.last_name
    print("JKKKJK")
    # print(user)
    # print(appointments)
    # #print(prescriptions[0].pdf)
    # #print(prescriptions[0].prescription_date)
    # if not appointments:
    #     context="Hurray No Pending Appointments"
    # else:
    #     context="Pending Appointments"
    # print(appointments[0].date)
    # print(appointments[0].time)
    return render(request,'work_history_home1.html',{'appointments':appointments,'first_name':first_name,'last_name':last_name})

templates/rmp/login.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load static %}


{% block login %}

    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <div class="container">
      <a href='{% url "home" %}' class="navbar-brand"><b>SMART HEALTHCARE SYSTEM</b></a>
      <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a href='{% url "home" %}' class="nav-link">Home</a>
          </li>
          <li class="nav-item">
            <a href='{% url "about" %}' class="nav-link">About Us</a>
          </li>
          <li class="nav-item">
            <a href='{% url "how_we_work" %}' class="nav-link">How we work</a>
          </li>
          <li class="nav-item">
            <a href='{% url "contact" %}' class="nav-link">Contact</a>
          </li>
          <li class="nav-item">
            <a href='{% url "login" %}' class="nav-link">Login</a>
          </li>
           <li class="nav-item active">
            <a href='{% url "rmp:login_rmp_profile" %}' class="nav-link">Rmp Login</a>
          </li>
         
        </ul>
      </div>
    </div>
  </nav>
<br>


  <div class="container">
    <div class="row">
      <div class="col-sm-9 col-md-6 col-lg-4 mx-auto">
        <div class="card card-signin my-5">
          <div class="card-body">
            <h3 class="card-title text-center font-weight-bold">Sign In</h3>

<form method='POST' class="form-signin mx-auto"> {%csrf_token %}

 {% for message in messages %}

                    <div class="alert alert-success">
                        <a class="close" href="#" data-dismiss="alert">×</a>

                        {{ message }}

                    </div>
            {% endfor %}

  {{ form.username | add_class:"form-control" | attr:"placeholder:Username"  }}<br>
  {{ form.password | add_class:"form-control" | attr:"placeholder:Password" }}<br>

  <button type='submit' class="btn btn-dark btn-block text-uppercase">Submit</button>



</form>
<a href='{%url "password_reset" %}'>Forgot password?</a><br>
<a href='{%url "rmp:user_register" %}'>Dont have a account?create one!</a>
</div>
        </div>
      </div>
    </div>
</div>

<br><br><br><br><br><br><br><br>
{% endblock %}

templates/rmp/make_rmp_profile.html
{% extends 'base1.html' %}

{% load static %}
{% load widget_tweaks %}

{% block make_rmp_profile %}



{% if error_message %}
  <p><strong>{{error_message}}</strong></p>
{% endif %}<br>

  <h1 style="text-align: center;">Please enter your details</h1><br>

   <div class='container-fluid'>
     <div class='row mx-auto'>
      <div class='col-sm-5 col-md-7 col-lg-3 mx-auto'>
            <div class="form-group">
            <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
              {% csrf_token %}

              First Name:{{ form.first_name | add_class:"form-control"  }}
              Profile pic (URL) {{ form.profile_photo | add_class:"form-control" }}
              Last Name:{{ form.last_name | add_class:"form-control" }}
              <!-- Email:{{ form.email_id | add_class:"form-control" }} -->
              Gender:{{ form.gender | add_class:"form-control"  }}
              <span class="text-danger small">{{form.mobile_no.errors}}</span>

              Mobile No:{{ form.mobile_no | add_class:"form-control" }}
              Qualification:{{ form.qualification | add_class:"form-control"}}
              Locality:{{ form.locality | add_class:"form-control" }}
              Hospital:{{ form.hospital | add_class:"form-control"}}

              <!-- {% for field in form %}
                <div class="form-group">
                  <div class="col-sm-offset-2 col-sm-10">
                    <span class="text-danger small">{{field.errors}}</span>
                  </div>
                  <label class="control-label col-sm-3 text-right">{{ field.label_tag}}</label>
                  <label class="col-sm-5 text-left">{{ field }}</label>
                </div>
              {% endfor %} -->




                  <button type="submit" class="btn btn-dark form-control">Submit</button>


          </form>
          </div>
        </div>
    </div>
  </div>


{% endblock %}

templates/rmp/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}
{% load static %}

{% block register %}

<link rel="stylesheet" href="{% static  'css/style.css' %}">



    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <div class="container">
      <a href='{% url "home" %}' class="navbar-brand"><b>SMART HEALTHCARE SYSTEM</b></a>
      <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a href='{% url "home" %}' class="nav-link">Home</a>
          </li>
          <li class="nav-item">
            <a href='{% url "about" %}' class="nav-link">About Us</a>
          </li>
          <li class="nav-item">
            <a href='{% url "how_we_work" %}' class="nav-link">How we work</a>
          </li>
          <li class="nav-item">
            <a href='{% url "contact" %}' class="nav-link">Contact</a>
          </li>
          <li class="nav-item active">
            <a href='{% url "login" %}' class="nav-link">Login</a>
          </li>
           <li class="nav-item">
            <a href='{% url "rmp:login_rmp_profile" %}' class="nav-link">Rmp Login</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

<body>
  <div class="container">
    <div class="row">
      <div class="col-sm-9 col-md-6 col-lg-4 mx-auto">
        <div class="card card-signin my-5">
          <div class="card-body">
             <h3 class="card-title text-center font-weight-bold">Sign Up</h3>
<form method='POST' class="form-signin mx-auto" >
{%csrf_token %}
                {% if form.errors %}
                    {% for field in form %}
                        {% for error in field.errors %}
                            <div class="alert alert-danger">
                                <strong>{{ error|escape }}</strong>
                            </div>
                        {% endfor %}
                    {% endfor %}
                    {% for error in form.non_field_errors %}
                        <div class="alert alert-danger">
                            <strong>{{ error|escape }}</strong>
                        </div>
                    {% endfor %}
                {% endif %}

  {{ form.username | add_class:"form-control" | attr:"placeholder:Username"  }}<br>
  {{ form.email | add_class:"form-control" | attr:"placeholder:email" }}<br>
  {{ form.password | add_class:"form-control" | attr:"placeholder:password"  }}<br>
  {{ form.password1 | add_class:"form-control" | attr:"placeholder:confirm password" }}<br>

  <button type='submit' class="btn btn-dark btn-block text-uppercase">Register</button>
<!-- sqqssqssq -->
</form>

</div>
        </div>
      </div>
    </div>
  </div>
</body>
<br><br><br><br><br><br>
{% endblock %}

templates/rmp/show_rmp_profile.html
{% extends 'base1.html' %}

{% load static %}

{% block show_rmp_profile  %}


<script>
function relocate_edit()
{
     location.href = "/profile/modify_profile";
}

function relocate_appointment()
{
     location.href = "/appointments/";
}
</script>

    <style>
      .checked{
        color: orange;
      }
      .button {
        border: none;
        color: black;
        background-color: #edecea;
        padding: 15px 25px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 20px;
        margin: 4px 2px;
        cursor: pointer;
    }
    .button:hover{
      background-color: rgb(244, 173, 66);
      color: white;
    }
    td{
      padding:15px 45px;
      font-size: 17px;
    }
    .heading_btn{
      padding:15px 45px;
      font-size: 20px;
      cursor: pointer;
    }
    .heading_btn:hover{
      background-color: rgb(244, 173, 66);
    }

    </style>


<div class="container-fluid" style="margin-top: 5%">
    <div class="row mx-auto">
      <div class="col-md-3 col-lg-3 mx-auto col-sm-0">
    <br>
        <div class="card">
           <img src="{{profile.profile_photo.url}}" alt="profile_photo" style="width:100%;min-height:400px">
        </div><br><br>
        <a href="{% url 'shopping_cart:order' %}">Shopping Order History</a><br><br>
        <a href="{% url 'shopping_cart:order_summary' %}">Current Pending Order</a>
        <br>



      </div>
      <div class="col-md-8 col-sm-offset-2">
        <div>
          <span style="font-size: 35px;">Dr. {{profile.first_name}} {{profile.last_name}}</span>&nbsp&nbsp&nbsp

        </div>
        <div style="margin-top: 7px;color: blue;font-size: 20px;" >
          {{profile.speciality}}
        </div>

          <br><br>


            <br><br>

          <div>
            <span class="heading_btn About" onclick=" about_display()">About</span>

          </div><hr>

            <br>

          <div style="display: none;" id="Experience">
            <span style="font-size: 17px;">Doctors's experience will be here.</span>
          </div>
          <div id ="About">
            <div style="padding: 15px 45px;font-size: 16px;opacity: 0.5;">
              BASIC INFORMATION
            </div><br>
            <div>
              <table>
                <tr>
                  <td>Locality</td>
                  <td>{{profile.locality}}</td>
                </tr>
                <tr>
                  <td>Gender</td>
                  <td>{{profile.gender}}</td>
                </tr>
              </table>
            </div><br>
            <div style="padding: 15px 45px;font-size: 16px;opacity: 0.5;">
              CONTACT INFORMATION
            </div><br>
            <table>
              <tr>
                <td>Phone</td>
                <td>+91{{profile.mobile_no}}</td>
              </tr>
              <tr>
                <td>Address</td>
                <td>{{profile.locality}}</td>
              </tr>
              <tr>
                <td>E-Mail</td>
                <td>{{profile.email_id}}</td>
              </tr>

            </table>
          </div>
      </div>
    </div>
  </div>

<br><br><br><br>
{% endblock %}

templates/rmp/work_history.html
{% extends 'base1.html' %}


{% load static %}

<!-- <!DOCTYPE html>
<html lang="en">
<head>
  <title>Prescription</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
   -->
  {% block work_history_rmp %}



  <div class="container-fluid">
    <!-- Right Song Info -->
          <div class="col-sm-8 col-md-9">

              <div class="panel panel-default">
                  <div class="panel-body">
                    <br>
                      <h3>&nbsp&nbspHello Dr. {{first_name}}  {{last_name}}  </h3>

                      {% if error_message %}
                          <p><strong>{{ error_message }}</strong></p>
                      {% endif %}

                      <table class="table">
                          <thead>
                          <tr>
                              <th>Appointment Date and time</th>
                              <th>Prescription</th>

                          </tr>
                          </thead>
                          <tbody>
                          {% for prescription in prescriptions %}
                              <tr>
                                  <td> {{prescription.prescription_date}}</td>
                                  <td><a href="/media/{{prescription.pdf}}"> Download Prescription </a></td>


                              </tr>
                          {% endfor %}
                          </tbody>
                      </table>

                  </div>
              </div>

          </div>

      </div>


      </br></br></br></br></br></br></br></br></br></br></br></br>
      {% endblock %}

</body>
</html>