myapp/urls.py
from django.conf.urls import url
from django.urls import include
from django.urls import path
from . import views
from django.urls import path
app_name="myapp"
urlpatterns = [
    url('^admin1/adminpage/$',views.adminpage,name='adminpage'),
    url('^admin1/doctorlist/$', views.index, name='myapp-index'),
    url('^admin1/rmplist/$', views.rmpdetails, name='myapp-rmpdetails'),
    path('admin1/rmplist/search/<pk>/',views.fullviewrmp, name='myapp-fullrmplist'),
    path('admin1/rmplist/fullview/rmpdetail/',views.rmpdetail,name='myapp-rmpdetail'),
    path('admin1/rmplist/fullview/patientdetails/<pk>/',views.patientdetails,name='myapp-patientdetail'),
    path('admin1/rmplist/search/rmp_upcoming_appointments/<pk>/', views.rmp_upcoming_appointments,name='rmp_upcoming_appointments'),
    path('admin1/rmplist/search/rmp_attended_appointments/<pk>/', views.rmp_attended_appointments,name='rmp_attended_appointments'),
    url('^admin1/payment/',views.payment,name='myapp-payment'),
    url('^admin1/doctor_verification/',views.doctor_verify,name='doctor_verification_required'),
    url('^admin1/rmp_verification/',views.rmp_verify,name='rmp_verification_required'),

    url('^admin1/appointment/',views.appointment,name='myapp-appointment'),
    url('^admin1/feedback/',views.feedback,name='myapp-feedback'),
    url('^admin1/newsletter/',views.newsletter,name='myapp-newsletter'),
    path('admin1/doctorlist/search/<pk>/',views.doctor_detail, name='doctor_detail'),
    path('admin1/doctorlist/search/doctor_upcoming_appointments/<pk>/',views.doctor_upcoming_appointments, name='doctor_upcoming_appointments'),
    path('admin1/doctorlist/search/doctor_attended_appointments/<pk>/',views.doctor_attended_appointments, name='doctor_attended_appointments'),
    path('admin1/doctorlist/search/slot/<pk>/',views.show_slots, name='doctor_slot'),

    path('admin1/doctor_verification/verify', views.doctor_verify_confirmation, name='doctor_verify'),
    # path('admin1/doctor_verification/verify/<pk>/',views.a, name='doctor_verify'),
    path('admin1/s/<pk>/',views.doctor_verify_confirmation,name='verify'),
    path('admin1/r/<pk>/',views.rmp_verify_confirmation,name='verify-rmp'),

    path('admin1/rmp_appointments_past/<pk>/',views.rmp_appointments_past, name='rmp_appointments_past'),
    path('admin1/online-shopping-history/',views.shop_history, name='shop_history'),
    path('admin1/order-history/<rmp_id>/',views.rmp_order_history, name='rmp_order_history'),

    url('',include('users.urls')),
]

payment/urls.py
from django.urls import path
from payment import views

app_name = 'payment'

urlpatterns = [
	path('online-payment/',views.payment_online_cod,name='payment_online_cod'),
]

prescription/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
app_name='prescription'
urlpatterns=[
    path('',views.index,name='index'),
    url(r'^prescription_add/(?P<appointment_id>[0-9]+)$',views.PrescriptionCreate.as_view(),name='Prescription_Add1'),
    path('prescription_add/',views.make_prescription,name='Prescription_Add'),
    url(r'^(?P<pk>[0-9]+)/$',views.DetailView.as_view(),name='detail'),
    url(r'^(?P<prescription_id>[0-9]+)/create_item/$', views.create_item, name='create_item'),
    path('name-autocomplete/',views.MedicineAutocomplete.as_view(),name='name-autocomplete'),
    url(r'^(?P<prescription_id>[0-9]+)/print/$', views.print, name='print'),

]

rmp/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from rmp.views import user_register, new_user_reg
from django.contrib.auth import views as auth_views
from users import views as user_views

app_name='rmp'

urlpatterns=[
    path('make_rmp_profile/',views.make_profile,name='make_rmp_profile'),
    path('modify_rmp_profile/',views.modify_profile,name='modify_rmp_profile'),
    path('show_rmp_profile/',views.Show_Profile,name='show_rmp_profile'),
    path('login/',views.login_page,name='login_rmp_profile'),
   # path('register/',views.register_page,name='make_rmp_profile'),
   url(r'^rmp/register/$',views.user_register , name='user_register' ),
   url(r'^rmp/new_user_reg/$',views.new_user_reg , name='new_user_reg' ),
   url(r'^password/change/$',
        auth_views.PasswordChangeView.as_view(),
        name='password_change'),
    url(r'^password/change/done/$',
        auth_views.PasswordChangeDoneView.as_view(),
        name='password_change_done'),
    url(r'^login/password/reset/$',
        auth_views.PasswordResetView.as_view(),
        name='password_reset'),
    url(r'^password/reset/done/$',
        auth_views.PasswordResetDoneView.as_view(),
        name='password_reset_done'),
    url(r'^password/reset/\
        (?P<uidb64>[0-9A-Za-z_\-]+)/\
        (?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'),
    url(r'^password/reset/complete/$',
        auth_views.PasswordResetCompleteView.as_view(),
        name='password_reset_complete'),

    ]

shoppingPortalApp/urls.py
from django.urls import path
from shoppingPortalApp import views

app_name = 'shoppingPortalApp'

urlpatterns = [
    path('',views.index,name='main'),
    path('add/',views.index_add,name='add_medicine'),
    path('action/<name>/',views.added,name='successful_add'),
    path('search/',views.result, name='result'),
    path('main/<name>/',views.showMedicine_name, name='medicine'),
    path('delete-edit/',views.index_delete_edit,name='del_edit_medicine'),
    path('delete/<med_id>',views.delete,name='delete'),
    path('edit/<med_id>',views.update_medicine,name='update_medicine'),
]

website/urls.py
from django.contrib import admin
from django.conf.urls import include
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import home, contact_page, login_page, about, contact, how_we_work,doctor_home,doctor_contact
from django.conf.urls import url
from django.conf import settings
from django.contrib import admin
from django.conf.urls import url, include


from .views import home_page, login_page,log_out,user_register, new_user_reg

from django.contrib.auth import views as auth_views
from users import views as user_views

# app_name='website'
urlpatterns = [

    path('', home, name='home'),
    path('admin/',admin.site.urls),
    path('logout/', log_out, name='logout'),
    path('contact_page/', contact_page , name='contact_page'),
    path('contact/', contact , name='contact'),
    path('doctor_contact/', doctor_contact , name='contact_doctor'),
    path('about/', about , name='about'),
    path('how_we_work/', how_we_work , name='how_we_work'),
    url(r'^doctor_home/$',doctor_home, name='doctor_home'),
    # url(r'^doctor_home/$',doctor_verification_required, name='doctor_verification_required'),
    url(r'^doctor/', include(("doctor_home.url","doctor"), namespace= 'doctor')),
    #(r'^$',home_page , name='home_page'),
    url(r'^login/$', login_page, name='login' ),
    url(r'^doctor/register/$',user_register , name='user_register' ),
    url(r'^doctor/new_user_reg/$',new_user_reg , name='new_user_reg' ),
    url(r'^password/change/$',
        auth_views.PasswordChangeView.as_view(),
        name='password_change'),
    url(r'^password/change/done/$',
        auth_views.PasswordChangeDoneView.as_view(),
        name='password_change_done'),
    url(r'^login/password/reset/$',
        auth_views.PasswordResetView.as_view(),
        name='password_reset'),
    url(r'^password/reset/done/$',
        auth_views.PasswordResetDoneView.as_view(),
        name='password_reset_done'),
    url(r'^password/reset/\
        (?P<uidb64>[0-9A-Za-z_\-]+)/\
        (?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'),
    url(r'^password/reset/complete/$',
        auth_views.PasswordResetCompleteView.as_view(),
        name='password_reset_complete'),

    path('restframework/', include('restframework.urls')),

    path('shoponline/', include('shoppingPortalApp.urls')),
    path('shoponline/', include('shopping_cart.urls')),
    path('payment/', include('payment.urls')),

    path('profile/',include('doctor_profile.urls')),
    path('disease/',include('disease.urls')),
    path('prescription/',include('prescription.urls')),
    path('rmp/booking/',include('booking.urls')),
    path('appointments/',include('show_appointments.urls'),name='show_appointments'),
    path('work_history/',include('work_history.urls')),
    path('rmp_work_history/',include('rmp_work_history.urls')),
    #url(r'^activate/$', activate, name='activate'),

    #path('account-activation-email-sent', account_activation_email_sent, name='account_activation_email_sent'),
   # path('activate/<uidb64>/token>', activate_account, name='activate'),
  #  path('resend-activation-link', generate_new_activation_link, name='resend_activation_link'),



    path('', include('myapp.urls'), name='myapp'),
    path('users/',include('users.urls'), name='users'),
    path('rmp/', include('rmp.urls')),
]

if settings.DEBUG:

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/models.py
from django.db import models
from django.contrib.auth.models import User
from doctor_profile.models import Profile
from rmp.models import rmpContact


class Post(models.Model):
    doctor_name = models.ForeignKey('doctor_profile.Profile', on_delete=models.CASCADE)


class Rmplist(models.Model):
    rmp_list = models.ForeignKey('rmp.rmpContact', on_delete=models.CASCADE)


class appointment(models.Model):
    patient_name = models.ForeignKey('booking.PaitentDetails', on_delete=models.CASCADE)
    booking = models.ForeignKey('booking.AppointmentDetials', on_delete=models.CASCADE)

class ContactForm(models.Model):
    first_name = models.CharField(max_length=250)
    last_name = models.CharField(max_length=500)
    email = models.EmailField()
    mobile_no = models.BigIntegerField()
    message = models.TextField()


class NewsLetter(models.Model):
    name = models.CharField(max_length=250)
    email = models.EmailField()

payment/models.py
from django.db import models

# Create your models here.


class bank(models.Model):
	bank_name = models.CharField(max_length=40)
	bank_id = models.CharField(max_length=10)
	def __str__(self):
		return self.bank_name

class bank_customer(models.Model):
	CARD_TYPE_CHOICES = (
			('Visa','Visa'),
			('Rupay','Rupay'),
			('Master Card','Master Card'),
		)
	Bank = models.ForeignKey(bank, on_delete=models.SET_NULL, null=True)
	customer_name = models.CharField(max_length=20)
	card_no = models.CharField(max_length=20)
	card_type = models.CharField(max_length=20, choices=CARD_TYPE_CHOICES)
	card_cvv = models.IntegerField()
	bank_balance = models.FloatField(default=3000)

	def __str__(self):
		return self.customer_name


class OnlinePayment(models.Model):
	transaction_id = models.CharField(max_length=20)
	amount_paid = models.IntegerField()
	customer = models.ForeignKey(bank_customer, on_delete=models.SET_NULL, null=True)

	def __str__(self):
		return self.transaction_id

myapp/forms.py
from django import forms

from myapp.models import ContactForm,NewsLetter


class contactForm(forms.ModelForm):
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    mobile_no = forms.IntegerField(required=True)
    message = forms.CharField(widget=forms.Textarea, required=True)

    class Meta:
        model = ContactForm
        fields = ['first_name','last_name','email','mobile_no','message',]

class newsLetter(forms.ModelForm):
	name = forms.CharField(required=True)
	email = forms.EmailField(required=True)

	class Meta:
		model = NewsLetter
		fields = ['name','email',]

payment/forms.py
from django import forms
from .models import *


class enter_payment_details(forms.ModelForm):
	class Meta:
		model = bank_customer
		fields = '__all__'
		exclude = ('bank_balance',)

payment/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.http import HttpResponse

from .models import *
from .forms import enter_payment_details
from shopping_cart.views import get_user_pending_order
from .extras import generate_order_id

# Create your views here.


def payment_online_cod(request):
	customers = bank_customer.objects.all()
	admin_bank = get_object_or_404(bank_customer, customer_name='Admin')
	if request.method=="POST":
		form=enter_payment_details(request.POST or None)
		if form.is_valid():
			cus_name = form.cleaned_data['customer_name']
			bank_name = form.cleaned_data['Bank']
			Card_no = form.cleaned_data['card_no']
			ctype = form.cleaned_data['card_type']
			cvv_bc = form.cleaned_data['card_cvv']
			instance = bank_customer.objects.filter(Bank=bank_name, customer_name=cus_name, card_no=Card_no, card_type=ctype, card_cvv=cvv_bc).first()
			if instance:
				transId = generate_order_id()
				current_order = get_user_pending_order(request)
				new_payment = OnlinePayment.objects.create(transaction_id=transId,amount_paid=current_order.get_cart_total(),customer=instance)
				instance.bank_balance = instance.bank_balance - current_order.get_cart_total()
				admin_bank.bank_balance = admin_bank.bank_balance + current_order.get_cart_total()
				instance.save()
				admin_bank.save()
				current_order.is_ordered = True
				return redirect(reverse('shopping_cart:purchase_success', kwargs={'payment_mode':'Online-Payment'}))
	else:
		form = enter_payment_details()
	return render(request,'payment/payment_details.html',{'form': form,'customers' : customers,})

myapp/templates/myapp/adminpage.html
{% load static %}
<!DOCTYPE HTML>
<html>
	<head>
		<title>Admin Page</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<link rel="stylesheet" href="{% static 'myapp/main1.css' %}" />
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" type="text/css">
		<link rel="stylesheet" type="text/css" href="all-ie-only.css" />
		<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous" />
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/fonts/fontawesome-webfont.eot" />
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/fonts/fontawesome-webfont.woff" />
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/fonts/fontawesome-webfont.woff2" />

	</head>
	<body class="landing">

		<!-- Header -->
			<header id="header" class="alt">
				<h1><a href="{% url 'myapp:myapp-index' %}">ADMIN PAGE</a></h1>
				<a href="#nav">Menu</a>
			</header>

		<!-- Nav -->
			<nav id="nav">
				<ul class="links">
          <li><a href="{% url 'myapp:myapp-index' %}">Doctor</a></li>
          <li><a href="{% url 'myapp:myapp-rmpdetails' %}">RMP Doctor</a></li>
					<li><a href='{% url "myapp:myapp-feedback" %}'>Feedbacks</a></li>
				   	<li><a href="{% url 'myapp:doctor_verification_required' %}"> Doctor-verification </a></li>
						<li><a href="{% url 'shoppingPortalApp:del_edit_medicine' %}">E - Medics Medicines</a></li>
						<li><a href="{% url 'myapp:shop_history' %}">Online Shopping History</a></li>
						<li><a href="{% url 'myapp:myapp-payment' %}">Payment History</a></li>
						<li><a href="{% url 'myapp:doctor_verification_required' %}"> Doctor-verification </a></li>
						<li><a href="{% url 'myapp:rmp_verification_required' %}"> RMP-verification</a></li>

				</ul>
			</nav>

		<!-- Banner -->
			<section id="banner">
				<i class="icon fa fa-user-md"></i>
				<h2>Smart</h2>
				<p> Health Care System</p>
			</section>

		<!-- One -->
			<section id="one" class="wrapper style1">
				<div class="inner">
					<article class="feature left">
						<span class="image"><img src="{% static 'myapp/images/pic01.jpg' %}" alt="" /></span>
						<div class="content">
							<h2>Doctor</h2>
							<p>To help the people to make them happy to slove their problems and make the HEALTHY</p>
							<ul class="actions">
								<li>
									<a href="{% url 'myapp:myapp-index' %}" class="button alt">Detail</a>
								</li>
							</ul>
						</div>
					</article>
					<article class="feature right">
						<span class="image"><img src="{% static 'myapp/images/pic02.jpg' %}" alt="" /></span>
						<div class="content">
							<h2>Rmp Doctor</h2>
							<p>Here,the doctor to help you even in rural areas</p>
							<ul class="actions">
								<li>
									<a href="{% url 'myapp:myapp-rmpdetails' %}" class="button alt">Detail</a>
								</li>
							</ul>
						</div>
					</article>
				</div>
			</section>

		<!-- Two -->
			<section id="two" class="wrapper special">
				<div class="inner">
					<header class="major narrow">
						<h2>Smart Health Care System</h2>
						<p>Here, the services we provide</p>
					</header>
					<div class="image-grid">
						<a href="{% url 'myapp:doctor_verification_required' %}" class="image"><img src="{% static 'myapp/images/pic03.jpg' %}" alt="" /></a>
						<a href="{% url 'myapp:myapp-index' %}" class="image"><img src="{% static 'myapp/images/pic04.jpg' %}" alt="" /></a>
						<a href="{% url 'myapp:myapp-payment' %}" class="image"><img src="{% static 'myapp/images/pic05.jpg' %}" alt="" /></a>
						<a href="{% url 'myapp:myapp-newsletter' %}" class="image"><img src="{% static 'myapp/images/pic06.jpg' %}" alt="" /></a>
						<a href="{% url 'myapp:myapp-rmpdetails' %}" class="image"><img src="{% static 'myapp/images/pic07.jpg' %}" alt="" /></a>
						<a href="{% url 'shoppingPortalApp:del_edit_medicine' %}" class="image"><img src="{% static 'myapp/images/pic08.jpg' %}" alt="" /></a>
						<a href="{% url 'myapp:myapp-feedback' %}" class="image"><img src="{% static 'myapp/images/pic09.jpg' %}" alt="" /></a>
						<a href="{% url 'myapp:myapp-appointment' %}" class="image"><img src="{% static 'myapp/images/pic10.jpg' %}" alt="" /></a>
					</div>
				</div>
			</section>

		<!-- Three -->
			<section id="three" class="wrapper style3 special">
				<div class="inner">
					<header class="major narrow	">
						<h2>Online Hospital</h2>
						<p>The art of medicine consists of amusing the patient while nature cures the disease</p>
					</header>
				</div>
			</section>

		<!-- Footer -->
			<footer id="footer">
				<div class="inner">
					<ul class="copyright">
						<li>&copy; Health@</li>
					</ul>
				</div>
			</footer>

		<!-- Scripts -->
			<!-- Scripts -->
			<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
			<script src="https://cdnjs.cloudflare.com/ajax/libs/skel/3.0.1/skel.min.js"></script>
			<script src="https://cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.min.js"></script>
			<script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.js"></script>
			<script src="{% static 'myapp/util.js' %}"></script>
			<script src="{% static 'myapp/main1.js' %}"></script>

	</body>
</html>

myapp/templates/myapp/attended_appointments.html
{% extends "myapp/base.html" %}
{% block content %}
<style>
        table {
            font-family: arial, sans-serif;
            border-collapse: collapse;
            width: 100%;
        }

        td, th {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 8px;
            font-size: 20px;
        }

        tr:nth-child(even) {
            background-color: #dddddd;
        }
        tr:nth-child(odd) {
            background-color: #a5a9ad;
        }
    </style>
        <div class="container-fluid">

                <div class="col-sm-8 col-md-12" style="padding-right:20px">

                    <div class="panel panel-default" style="padding-right:20px">
                        <div class="panel-body">
                          <br>

                      {% if error_message %}
                          <p><strong>{{ error_message }}</strong></p>
                      {% endif %}
                      <br>
                      <table class="table table-striped table-hover ">
                          <thead>
                          <tr>
                              <th>Date</th>
                              <th>Time</th>
                              <th>Patient Name</th>
                              <!-- <th>RMP Name </th> -->
                              <th>Symptoms</th>
                              <th>Prescription </th>


                          </tr>
                          </thead>
                          <tbody>
                          {% for appointment in appointments %}
                      
                              <tr>
                                  <td id="a"> {{appointment.date.date}}</td>
                                  <td id="b"> {{appointment.time.start_time}}</td>
                                  <td> {{appointment.paitent.first_name}} {{appointment.paitent.last_name}}</td>
                                  <td> {{appointment.paitent.symptoms}}</td>
                                  <!-- <td><a style="pointer-events: none; display: inline-block;" id='attend{{appointment.id}}' href="{{appointment.viedo_chat_link}}"> Attend Patient </a></td>
                                  <td><a style="pointer-events: none; display: inline-block;" id='prescription{{appointment.id}}' href='{% url "prescription:Prescription_Add1" appointment_id=appointment.pk %}'> Make Prescription </a></td> -->
                                  <!-- <td><button type="button" name="check" onclick='check_link("{{appointment.date}}","{{appointment.time.start_time}}","{{appointment.id}}");'> Refresh </button> -->
                                  <td><a href="/media/{{appointment.prescription.pdf}}"> Download Prescription </a></td>

                              </tr>
                          {% endfor %}
                          </tbody>
                      </table>
                      <div class="alert alert-warning">
                          {{context}}
                      </div>

                  </div>
              </div>

          </div>

      </div>
{% endblock %}

myapp/templates/myapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous" />

    <link rel="stylesheet" type="text/css" href="{% static 'myapp/main.css' %}">
    <title class="icon fa fa-user-md">Admin Panel</title>
</head>
<body>
<header class="site-header" style="color:#000000 ">
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <div class="container">
            <a class="navbar-brand icon fa fa-user-md" style="font-size: 30px" href="{% url 'myapp:adminpage' %}">&nbsp&nbspADMIN PANEL</a>
            <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a href='{% url "myapp:myapp-index" %}' class="nav-link">DOCTOR</a>
                    </li>
                    <li class="nav-item">
                        <a href='{% url "myapp:myapp-rmpdetails" %}' class="nav-link">RMP DOCTOR</a>
                    </li>
                    <li class="nav-item">
                        <a href='{% url "myapp:myapp-payment" %}' class="nav-link">Payments</a>
                    </li>
                    <li class="nav-item">
                        <a href='{% url "myapp:myapp-feedback" %}' class="nav-link">Feedbacks</a>
                    </li>
                    <li class="nav-item">
                        <a href='{% url "myapp:myapp-newsletter" %}' class="nav-link">NewsLetters</a>
                    </li>
                    <li class="nav-item">
                        <a href='{% url "logout" %}' class="nav-link">Logout</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<main role="main" class="container">
    <div class="row">
        <div class="col-md-10">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
            {% block content %}{% endblock %}
        </div>
    </div>
</main>
{% block total_orders %}{% endblock total_orders %}
<br><br><br><br><br><br><br><br>
<br><br><br><br><br><br><br><br>

 <footer id="main-footer" class="text-center p-4" style="background-color: black; color: #fff;">
    <div class="container">
      <div class="row">
        <div class="col">
          <p>Copyright &copy;
            <span id="year"></span> Smart HealthCare</p>
        </div>
      </div>
    </div>
  </footer>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

myapp/templates/myapp/feedback.html
{% extends 'myapp/base.html' %}
{% block content %}
    <h3>yet to complete </h3>
{% endblock content %}

myapp/templates/myapp/profile.html
{% extends "myapp/base.html" %}
{% block content %}
{% for temp in x %}

    {{ temp.doctor_name.first_name }}
    {{ temp.doctor_name.gender }}
    {{ temp.doctor_name.last_name }}

{% endfor %}
{% endblock content %}