prescription/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
app_name='prescription'
urlpatterns=[
    path('',views.index,name='index'),
    url(r'^prescription_add/(?P<appointment_id>[0-9]+)$',views.PrescriptionCreate.as_view(),name='Prescription_Add1'),
    path('prescription_add/',views.make_prescription,name='Prescription_Add'),
    url(r'^(?P<pk>[0-9]+)/$',views.DetailView.as_view(),name='detail'),
    url(r'^(?P<prescription_id>[0-9]+)/create_item/$', views.create_item, name='create_item'),
    path('name-autocomplete/',views.MedicineAutocomplete.as_view(),name='name-autocomplete'),
    url(r'^(?P<prescription_id>[0-9]+)/print/$', views.print, name='print'),

]

rmp/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from rmp.views import user_register, new_user_reg
from django.contrib.auth import views as auth_views
from users import views as user_views

app_name='rmp'

urlpatterns=[
    path('make_rmp_profile/',views.make_profile,name='make_rmp_profile'),
    path('modify_rmp_profile/',views.modify_profile,name='modify_rmp_profile'),
    path('show_rmp_profile/',views.Show_Profile,name='show_rmp_profile'),
    path('login/',views.login_page,name='login_rmp_profile'),
   # path('register/',views.register_page,name='make_rmp_profile'),
   url(r'^rmp/register/$',views.user_register , name='user_register' ),
   url(r'^rmp/new_user_reg/$',views.new_user_reg , name='new_user_reg' ),
   url(r'^password/change/$',
        auth_views.PasswordChangeView.as_view(),
        name='password_change'),
    url(r'^password/change/done/$',
        auth_views.PasswordChangeDoneView.as_view(),
        name='password_change_done'),
    url(r'^login/password/reset/$',
        auth_views.PasswordResetView.as_view(),
        name='password_reset'),
    url(r'^password/reset/done/$',
        auth_views.PasswordResetDoneView.as_view(),
        name='password_reset_done'),
    url(r'^password/reset/\
        (?P<uidb64>[0-9A-Za-z_\-]+)/\
        (?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'),
    url(r'^password/reset/complete/$',
        auth_views.PasswordResetCompleteView.as_view(),
        name='password_reset_complete'),

    ]

show_appointments/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
app_name='show_appointments'
urlpatterns=[
path('',views.index,name='index'),
path('slot',views.show_slots,name='show_slots')
];

website/urls.py
from django.contrib import admin
from django.conf.urls import include
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import home, contact_page, login_page, about, contact, how_we_work,doctor_home,doctor_contact
from django.conf.urls import url
from django.conf import settings
from django.contrib import admin
from django.conf.urls import url, include


from .views import home_page, login_page,log_out,user_register, new_user_reg

from django.contrib.auth import views as auth_views
from users import views as user_views

# app_name='website'
urlpatterns = [

    path('', home, name='home'),
    path('admin/',admin.site.urls),
    path('logout/', log_out, name='logout'),
    path('contact_page/', contact_page , name='contact_page'),
    path('contact/', contact , name='contact'),
    path('doctor_contact/', doctor_contact , name='contact_doctor'),
    path('about/', about , name='about'),
    path('how_we_work/', how_we_work , name='how_we_work'),
    url(r'^doctor_home/$',doctor_home, name='doctor_home'),
    # url(r'^doctor_home/$',doctor_verification_required, name='doctor_verification_required'),
    url(r'^doctor/', include(("doctor_home.url","doctor"), namespace= 'doctor')),
    #(r'^$',home_page , name='home_page'),
    url(r'^login/$', login_page, name='login' ),
    url(r'^doctor/register/$',user_register , name='user_register' ),
    url(r'^doctor/new_user_reg/$',new_user_reg , name='new_user_reg' ),
    url(r'^password/change/$',
        auth_views.PasswordChangeView.as_view(),
        name='password_change'),
    url(r'^password/change/done/$',
        auth_views.PasswordChangeDoneView.as_view(),
        name='password_change_done'),
    url(r'^login/password/reset/$',
        auth_views.PasswordResetView.as_view(),
        name='password_reset'),
    url(r'^password/reset/done/$',
        auth_views.PasswordResetDoneView.as_view(),
        name='password_reset_done'),
    url(r'^password/reset/\
        (?P<uidb64>[0-9A-Za-z_\-]+)/\
        (?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'),
    url(r'^password/reset/complete/$',
        auth_views.PasswordResetCompleteView.as_view(),
        name='password_reset_complete'),

    path('restframework/', include('restframework.urls')),

    path('shoponline/', include('shoppingPortalApp.urls')),
    path('shoponline/', include('shopping_cart.urls')),
    path('payment/', include('payment.urls')),

    path('profile/',include('doctor_profile.urls')),
    path('disease/',include('disease.urls')),
    path('prescription/',include('prescription.urls')),
    path('rmp/booking/',include('booking.urls')),
    path('appointments/',include('show_appointments.urls'),name='show_appointments'),
    path('work_history/',include('work_history.urls')),
    path('rmp_work_history/',include('rmp_work_history.urls')),
    #url(r'^activate/$', activate, name='activate'),

    #path('account-activation-email-sent', account_activation_email_sent, name='account_activation_email_sent'),
   # path('activate/<uidb64>/token>', activate_account, name='activate'),
  #  path('resend-activation-link', generate_new_activation_link, name='resend_activation_link'),



    path('', include('myapp.urls'), name='myapp'),
    path('users/',include('users.urls'), name='users'),
    path('rmp/', include('rmp.urls')),
]

if settings.DEBUG:

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

work_history/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
app_name='work_history'
urlpatterns=[
path('',views.index1,name='index'),
];

prescription/models.py
from django.db import models
from django.urls import reverse
from doctor_profile.models import Profile
from django.urls import reverse
from doctor_profile.models import Profile


class Prescription(models.Model):
    doctor=models.ForeignKey(Profile,on_delete=models.CASCADE,null=True,blank=True)
    prescription_id=models.CharField(max_length=30,unique=True)
    prescription_date=models.DateTimeField(auto_now_add=True)
    pdf= models.FileField(upload_to='media_/pdf/', null=True, blank=True)

    def __str__(self):
        return self.prescription_id

    def get_absolute_url(self):
        return reverse('prescription:detail',kwargs={'pk':self.pk})



class Item(models.Model):
    prescription=models.ForeignKey(Prescription,on_delete=models.CASCADE)
    medicine_name=models.CharField(max_length=100,blank=False)
    days=models.BigIntegerField()
    morning=models.BooleanField(default=True)
    afternoon=models.BooleanField(default=True)
    night=models.BooleanField(default=True)



    def __str__(self):
        return self.medicine_name

class Medicine(models.Model):
    name=models.CharField(max_length=50)

    def __str__(self):
        return self.name

    def index_queryset(self, using=None):
        return self.get_model().objects.filter(name__lte=self.name)

prescription/forms.py
from django import forms
from .models import Prescription, Item
from dal import autocomplete
from .models import Medicine
class Make_Prescription(forms.ModelForm):
    class Meta:
        model=Prescription
        fields='__all__'

class ItemForm(forms.ModelForm):
    medicine_name = forms.ModelChoiceField(
                queryset=Medicine.objects.all(),
                widget=autocomplete.ModelSelect2(url='prescription:name-autocomplete',
                attrs={
                'data-placeholder': 'Medicine-name',
                #'data-minimum-input-length': 1,
                })
            )
    class Meta:
        model = Item
        fields = '__all__'

prescription/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404, redirect
from .models import Prescription,Item
from .models import Medicine
from django.http import HttpResponse
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import View
from .forms import Make_Prescription,ItemForm
from django.views import generic
from django.db.models import Max
from dal import autocomplete
from .utils import render_to_pdf
from django.template.loader import get_template
from io import BytesIO
from django.core.files import File
from doctor_profile.models import Profile
from django.views.generic import FormView, CreateView
from booking.models import AppointmentDetials
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required

# Create your views here.
from django.contrib.auth.models import User
def index(request):
    return render(request,'prescription_home.html')

@login_required(login_url=reverse_lazy('login'))
def make_prescription(request):
    if request.method=="POST":
        form=Make_Prescription(request.POST)
        if form.is_valid():
            profile_item=form.save(commit=False)
            profile_item.save()
            #return redirect('/profile/show_profile/'+str(profile_item.doctor_id))
    else:
        form=Make_Prescription()
    return render(request,'new_file.html',{'form':form})

class DetailView(generic.DetailView):
    model=Prescription
    template_name='detail.html'


class PrescriptionCreate(CreateView):


    model=Prescription
    fields=['prescription_id',]
#################################TO PASS INITIAL VALUES ############
    def get_initial(self):
        #appointment_id=appointment_id
        max_id=Prescription.objects.all().aggregate(Max('prescription_id'))
        if list(max_id.values())[0] == None:
            value=0
        else:
            value=int(list(max_id.values())[0])
        value=value+1
        #user = request.user


        #print(value)
        #appointment_id=self.kwargs['appointment_id']
        initial = super(PrescriptionCreate, self).get_initial()
        initial.update({'prescription_id': value})
        return initial

    def get_context_data(self, **kwargs):
        context = super(PrescriptionCreate, self).get_context_data(**kwargs)
        user=self.request.user
        profile = Profile.objects.get(user=user)
        #appointment_id=int(self.kwargs['appointment_id'])
        appointment = AppointmentDetials.objects.get(pk=self.kwargs['appointment_id'])
        context['appointment']=appointment
        context['doctor']=profile
        return context



    def form_valid(self, form):
        #event = Event.objects.get(pk=self.kwargs['appointment_id'])
        user=self.request.user
        profile = Profile.objects.get(user=user)
        #appointment_id=int(self.kwargs['appointment_id'])

        #print('**')
        prescription = form.save(commit=False)

        prescription.doctor = profile
        prescription=form.save()
        appointment = AppointmentDetials.objects.get(pk=self.kwargs['appointment_id'])
        appointment.is_attended=True
        appointment.prescription=prescription
        appointment.save()
        return super(PrescriptionCreate, self).form_valid(form)

@login_required(login_url=reverse_lazy('login'))
def detail(request, pk):
    prescription = get_object_or_404(Prescription, pk=pk)
    return render(request, 'prescription/detail.html', {'prescription':prescription,'prescription_id':pk})

@login_required(login_url=reverse_lazy('login'))
def create_item(request, prescription_id):
    form = ItemForm(request.POST or None, request.FILES or None , initial={'prescription':prescription_id})
    prescription = get_object_or_404(Prescription, pk=prescription_id)
    if form.is_valid():
        prescription_items = prescription.item_set.all()
        for s in prescription_items:
            if s.medicine_name == form.cleaned_data.get("name"):
                context = {
                    'prescription': prescription,
                    'form': form,
                    #'error_message': 'You already added that medicine',
                }
                return render(request, 'prescription/create_item.html', context)
        item = form.save(commit=False)
        item.prescription = prescription
        item.save()
        return render(request, 'detail.html', {'prescription': prescription})
    context = {
        'prescription': prescription,
        'form': form,
    }
    return render(request, 'prescription/create_item.html', context)


class MedicineAutocomplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        qs = Medicine.objects.all()

        if self.q:
            qs = qs.filter(name__istartswith=self.q)
        #print(qs)
        return qs


def print(request,prescription_id):
    prescription = get_object_or_404(Prescription, pk=prescription_id)
    prescription_no=int(prescription_id)
    prescription_no=prescription_no-54

    template=get_template('prescription/print.html')
    context={"prescription_id":str(prescription_no),"prescription":prescription}
    html=template.render(context)
    pdf=render_to_pdf('prescription/print.html',context)
    filename ="prescription{}.pdf".format(prescription_id)

    if pdf:
        prescription.pdf.save(filename,File(BytesIO(pdf.content)))
        return HttpResponse(pdf,content_type='application/pdf')

    return HttpResponse('NOT FOUND')

prescription/templates/prescription/create_item.html
{% extends 'base.html' %}
{% load static %}
{% block prescription_item %}



         <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
         <div class="container">
           <a href='{% url "home" %}' class="navbar-brand"><b>SMART HEALTHCARE SYSTEM</b></a>
           <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
             <span class="navbar-toggler-icon"></span>
           </button>
           <div class="collapse navbar-collapse" id="navbarCollapse">
             <ul class="navbar-nav ml-auto">
               <li class="nav-item">
                 <a href='{% url "doctor_home" %}' class="nav-link">Home</a>
               </li>

                 <li class="nav-item">
                <a href='{% url "show_appointments:index" %}' class="nav-link">Show Appointments</a>
               </li>
               <li class="nav-item">
                 <a href='{% url "work_history:index" %}' class="nav-link">Work History</a>
               </li>
               <li class="nav-item active">
                 <a href='{% url "logout" %}' class="nav-link">Logout</a>
               </li>
             </ul>
           </div>
         </div>
       </nav>


  <div class="col-sm-8 col-md-9">


            <br>
            &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<a href="{% url 'prescription:detail' prescription.id %}" alt="link" style="text-decoration:none;"><button class="btn btn-primary" type="submit">View Prescription </button></a>
            <br>
  </div><br>
<div class="panel panel-default">
                <div class="panel-body col-sm-offset-2 col-sm-3 text-right">
                    <h3>Add a New Medicine</h3><br>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                  </div>
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        <div class="form-group col-sm-offset-2 col-sm-3 text-right" style="border-color:solid black">
                      {% csrf_token %}
                      {% include 'prescription/create_item_template.html' %}

                        </div>
                        <div class="col-sm-offset-2 col-sm-2 text-right">
                          <button type="submit" class="btn btn-success">Submit</button>
                        </div>

                    </form>

            <br><br><br>
{% endblock %}

prescription/templates/prescription/create_item_template.html
{% load static %}

{% for field in form %}
  <div class="form-group text">
    <div class="col-sm-offset-2 col-sm-10">
      <span class="text-danger small">{{field.errors}}</span>
    </div>
    <label class="control-label col-sm-3 text-right">{{ field.label_tag}}</label>
    <label class="col-sm-5 text-left">{{ field }}</label>
  </div>
{% endfor %}
<script type="text/javascript" src="{% static 'admin/js/vendor/jquery/jquery.js' %}"></script>
{{form.media}}

prescription/templates/prescription/prescription-template.html
{% for field in form %}
  <div class="form-group ">
    <div class="col-sm-offset-2 col-sm-10">
      <span class="text-danger small">{{field.errors}}</span>
    </div>
    <label class="control-label col-sm-5"> &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp &nbsp&nbsp&nbsp{{ field.label_tag}}</label>
    <label class="col-sm-5">{{ field }}</label>
  </div>
{% endfor %}

prescription/templates/prescription/prescription_form.html
<style>

button {
  border: none;
  outline: 0;
  display: inline-block;
  padding: 8px;
  color: white;
  background-color: #000;
  text-align: center;
  cursor: pointer;
  width: 100%;
  font-size: 18px;
}

a {
  text-decoration: none;
  font-size: 22px;
  color: black;
}

button:hover, a:hover {
  opacity: 0.7;
}

.payment-form{
  padding-bottom: 100px;
  font-family: 'Montserrat', sans-serif;
}


.payment-form .content{
  box-shadow: 0px 2px 10px rgba(0, 0, 0, 0.075);
  background-color: white;

}

.payment-form .block-heading{
    padding-top: 50px;
    margin-bottom: 0px;
    text-align: center;

}

.payment-form .block-heading p{
  text-align: center;
  max-width: 420px;
  margin: auto;
  opacity:0.7;
}

.payment-form.dark .block-heading p{
  opacity:0.8;
}

.payment-form .block-heading h1,
.payment-form .block-heading h2,
.payment-form .block-heading h3 {
  margin-bottom:1.2rem;

}


.payment-form .title{
  font-size: 1em;
  border-bottom: 1px solid rgba(0,0,0,0.1);
  margin-bottom: 0.8em;
  font-weight: 600;
  padding-bottom: 8px;
}

.payment-form .products{
  background-color: #f7fbff;
    padding: 25px;
     max-width: 500px;

}

.payment-form .products .item{
  margin-bottom:1em;
}

.payment-form .products .item-name{
  font-weight:600;
  font-size: 0.9em;
}

.payment-form .products .item-description{
  font-size:0.8em;
  opacity:0.6;
}

.payment-form .products .item p{
  margin-bottom:0.2em;
}

.payment-form .products .price{
  float: center;
  font-weight: 600;
  font-size: 0.9em;
}

.payment-form .products .total{
  border-top: 1px solid rgba(0, 0, 0, 0.1);
  margin-top: 10px;
  padding-top: 19px;
  font-weight: 600;
  line-height: 1;
}





</style>

{% extends 'base.html' %}


{% load static %}
-- NAV BAR -->


  {% block prescription_home %}
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
  <div class="container">
    <a href="index.html" class="navbar-brand"><b>SMART HEALTHCARE SYSTEM</b></a>
    <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a href='{% url "doctor_home" %}' class="nav-link">Home</a>
        </li>

        <li class="nav-item">
          <a href='{% url "how_we_work" %}' class="nav-link">How we work</a>
        </li>
        <li class="nav-item">
          <a href='{% url "contact" %}' class="nav-link">Contact</a>
        </li>
        <li class="nav-item">
          <a href='{% url "show_appointments:index" %}' class="nav-link">Show Appointments</a>
        </li>
        <li class="nav-item">
          <a href='{% url "work_history:index" %}' class="nav-link">Work History</a>
        </li>
        <li class="nav-item active">
          <a href='{% url "logout" %}' class="nav-link">Logout</a>
        </li>
      </ul>
    </div>
  </div>
  </nav>

  <div class="container-fluid" style="background-image:url({% static 'img/prescription.jpg' %});background-repeat; background-size:cover;height:530px">

    <main class="page payment-page">
   <section class="payment-form dark">
     <div class="container">
       <div class="block-heading">

         <button style="width:45%;height:10%"class="btn btn-primary" type="submit">Make Prescription</button>
       </div>

         <div class="products mx-auto ">
           <h1 class="title">Prescription</h1>
           <div class="item col-sm-12">
             <span class="price col-sm-5"> &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspDoctor : </span>

              <span class="price col-sm-6"> &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp Dr.{{doctor.first_name}} {{doctor.last_name}}</span>
              <br>
              <!-- <p class="item-name col-sm-6">Doctor-Name : </p> -->
            </div>
            <div class="item col-sm-offset-2 col-sm-12">
              <span class="price col-sm-5">&nbsp &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspPatient : </span>

               <span class="price col-sm-6"> &nbsp&nbsp&nbsp&nbsp Dr.{{appointment.paitent.first_name}} {{appointment.paitent.last_name}}</span>
               <br>
               <!-- <p class="item-name col-sm-6">Doctor-Name : </p> -->
             </div>
           <div class="item">
             <span class="price"><form class="form-horizonatal" action="" method="post">
               {% csrf_token %}
               {% include 'prescription/prescription-template.html' %}
               <div class="form-group">
                 <div class="col-sm-offset-2 col-sm-12">

                   <button type="submit" class="btn btn-success">Submit </button>
                   </div>
                   </div></span>


           </div>


         </div>


           </div>
         </div>

     </div>
   </section>

    </div>

{% endblock %}

prescription/templates/prescription/print.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">

<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
 <html>
     <head>
         <title>Title</title>
         <style type="text/css">
             body {
                 font-weight: 200;
                 font-size: 14px;
             }
             .header {
                 font-size: 20px;
                 font-weight: 100;
                 text-align: center;
                 color: #007cae;
             }
             .title {
                 font-size: 22px;
                 font-weight: 100;
                /* text-align: right;*/
                padding: 10px 20px 0px 20px;
             }
             .title span {
                 color: #007cae;
             }
             .details {
                 padding: 10px 20px 0px 20px;
                 text-align: left !important;
                 /*margin-left: 40%;*/
             }
             .hrItem {
                 border: none;
                 height: 1px;
                 /* Set the hr color */
                 color: #333; /* old IE */
                 background-color: #fff; /* Modern Browsers */
             }
         </style>
     </head>
     <body>
         <div class='wrapper'>
             <div class='header'>
                 <p class='title'>Prescription No. {{prescription_id}} </p>
             </div>
              <hr class='hrItem' />
               <!-- <hr class='hrItem' /> -->
         <div>
         <div class='details'>
             Patient Name:{{prescription.appointment.paitent.first_name}} {{paitent.appointment.paitent.last_name}}<br/>
             Doctor Name :Dr. {{prescription.doctor.first_name}} {{prescription.doctor.last_name}}<br>
             Date and Time:{{prescription.prescription_date}}
             <br><br>
             Prescription Computer Generated Signature Not Required
             <hr class='hrItem' />
         </div>
     </div>
     <div class="container-fluid songs-container">
       <!-- Right Song Info -->
             <div class="col-sm-8 col-md-9">

                 <div class="panel panel-default">
                     <div class="panel-body">

                         <!-- <h3>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspAll Medicines</h3> -->

                         {% if error_message %}
                             <p><strong>{{ error_message }}</strong></p>
                         {% endif %}

                         <table class="table">
                             <thead>
                             <tr>
                                 <th>Medicine Name</th>
                                 <th>Days</th>
                                 <th>Morning</th>
                                 <th>Afternoon</th>
                                 <th>Night</th>
                             </tr>
                             </thead>
                             <tbody>
                             {% for item in prescription.item_set.all %}
                                 <tr>
                                     <td>&nbsp&nbsp&nbsp&nbsp&nbsp{{ item.medicine_name }}</td>
                                     <td>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp{{ item.days}}</td>
                                     <td>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp{{ item.morning}}</td>
                                     <td>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp{{ item.afternoon}}</td>
                                     <td>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp{{ item.night}}</td>

                                 </tr>
                                  <hr class='hrItem' />
                             {% endfor %}
                             </tbody>
                         </table>

                     </div>
                 </div>

             </div>

         </div>
         <hr class='hrItem' />
         <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
         <center>

         <h2> GET WELL SOON <br> BEST WISHES FROM SMART HEALTHCARE SYSTEM </h2>
         </center>


     </body>
 </html>